version: "3.8"

services:
  db:
    image: postgres:16
    container_name: lamorada_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lamorada_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: lamorada_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: samuelgiraldoroldan51@gmail.com
      PGADMIN_DEFAULT_PASSWORD: zeusysamu9
    ports:
      - "5051:80"
    depends_on:
      - db

volumes:
  pgdata: